// <auto-generated />
using System;
using BookingSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace BookingSystem.Migrations
{
    [DbContext(typeof(ModelContext))]
    [Migration("20240814101019_editDataBase")]
    partial class editDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("C##SHAIMAA2")
                .UseCollation("USING_NLS_COMP")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingSystem.Models.Aboutusdatum", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Imgpath1")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IMGPATH1");

                    b.Property<string>("Imgpath2")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IMGPATH2");

                    b.Property<string>("Imgpath3")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IMGPATH3");

                    b.Property<string>("Imgpath4")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IMGPATH4");

                    b.Property<string>("Title")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(25)")
                        .HasColumnName("TITLE");

                    b.HasKey("Id")
                        .HasName("SYS_C008631");

                    b.ToTable("ABOUTUSDATA", "C##SHAIMAA2");
                });

            modelBuilder.Entity("BookingSystem.Models.Booking", b =>
                {
                    b.Property<decimal>("Bookingid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("BOOKINGID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Bookingid"));

                    b.Property<DateTime?>("Checkin")
                        .HasColumnType("DATE")
                        .HasColumnName("CHECKIN");

                    b.Property<DateTime?>("Checkout")
                        .HasColumnType("DATE")
                        .HasColumnName("CHECKOUT");

                    b.Property<decimal?>("CustomerId")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal?>("Numberofpersons")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("NUMBEROFPERSONS");

                    b.Property<decimal?>("Roomid")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ROOMID");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.Property<decimal?>("Totalprice")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTALPRICE");

                    b.HasKey("Bookingid")
                        .HasName("SYS_C008623");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Roomid");

                    b.ToTable("BOOKING", "C##SHAIMAA2");
                });

            modelBuilder.Entity("BookingSystem.Models.Customer", b =>
                {
                    b.Property<decimal>("CustomerId")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FirstName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("LastName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers", "C##SHAIMAA2");
                });

            modelBuilder.Entity("BookingSystem.Models.Homedatum", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Imgpath1")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IMGPATH1");

                    b.Property<string>("Imgpath2")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IMGPATH2");

                    b.Property<string>("Imgpath3")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IMGPATH3");

                    b.Property<string>("Logopath")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("LOGOPATH");

                    b.Property<string>("Title")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(25)")
                        .HasColumnName("TITLE");

                    b.HasKey("Id")
                        .HasName("SYS_C008629");

                    b.ToTable("HOMEDATA", "C##SHAIMAA2");
                });

            modelBuilder.Entity("BookingSystem.Models.Hotel", b =>
                {
                    b.Property<decimal>("Hotelid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("HOTELID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Hotelid"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(35)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(35)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(35)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(35)")
                        .HasColumnName("CITY");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(35)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(35)")
                        .HasColumnName("COUNTRY");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(35)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(35)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Imagepath")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IMAGEPATH");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(35)")
                        .HasColumnName("NAME");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("PHONENUMBER");

                    b.HasKey("Hotelid")
                        .HasName("SYS_C008615");

                    b.ToTable("HOTEL", "C##SHAIMAA2");
                });

            modelBuilder.Entity("BookingSystem.Models.Role", b =>
                {
                    b.Property<decimal>("RoleId")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("RoleName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles", "C##SHAIMAA2");
                });

            modelBuilder.Entity("BookingSystem.Models.Room", b =>
                {
                    b.Property<decimal>("Roomid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ROOMID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Roomid"));

                    b.Property<decimal?>("Availabilty")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("AVAILABILTY");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<decimal?>("Hotelid")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("HOTELID");

                    b.Property<string>("Imagepath")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IMAGEPATH");

                    b.Property<decimal?>("Maxcapacity")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("MAXCAPACITY");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(35)")
                        .HasColumnName("NAME");

                    b.Property<decimal?>("Price")
                        .HasColumnType("NUMBER")
                        .HasColumnName("PRICE");

                    b.Property<string>("Roomtype")
                        .IsRequired()
                        .HasMaxLength(35)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(35)")
                        .HasColumnName("ROOMTYPE");

                    b.HasKey("Roomid")
                        .HasName("SYS_C008620");

                    b.HasIndex("Hotelid");

                    b.ToTable("ROOM", "C##SHAIMAA2");
                });

            modelBuilder.Entity("BookingSystem.Models.Testimonial", b =>
                {
                    b.Property<decimal>("Testimonialid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("TESTIMONIALID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Testimonialid"));

                    b.Property<decimal?>("CustomerId")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal?>("Hotelid")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("HOTELID");

                    b.Property<string>("Reviewtext")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("REVIEWTEXT");

                    b.Property<string>("Status")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Testimonialid")
                        .HasName("SYS_C008626");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Hotelid");

                    b.ToTable("TESTIMONIAL", "C##SHAIMAA2");
                });

            modelBuilder.Entity("BookingSystem.Models.UserLogin", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal?>("CustomerId")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal?>("RoleId")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("UserName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserLogins", "C##SHAIMAA2");
                });

            modelBuilder.Entity("BookingSystem.Models.Booking", b =>
                {
                    b.HasOne("BookingSystem.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("BookingSystem.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("Roomid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("SYS_C008624");

                    b.Navigation("Customer");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("BookingSystem.Models.Room", b =>
                {
                    b.HasOne("BookingSystem.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("Hotelid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("SYS_C008621");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("BookingSystem.Models.Testimonial", b =>
                {
                    b.HasOne("BookingSystem.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("BookingSystem.Models.Hotel", "Hotel")
                        .WithMany("Testimonials")
                        .HasForeignKey("Hotelid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("SYS_C008627");

                    b.Navigation("Customer");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("BookingSystem.Models.UserLogin", b =>
                {
                    b.HasOne("BookingSystem.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("BookingSystem.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Customer");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BookingSystem.Models.Hotel", b =>
                {
                    b.Navigation("Rooms");

                    b.Navigation("Testimonials");
                });

            modelBuilder.Entity("BookingSystem.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
